notifications:
  email: false
addons:
  apt:
    packages:
    - libgdal1i
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev
language: python
python:
  - "3.6"
  - "3.7"

# Required for Python 3.7 to work:
sudo: required
dist: xenial

# Install dependencies
before_install:
- pip install poetry
install:
- poetry install -v

# Run tests
script: pytest
